# Generated by Django 5.0.14 on 2026-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Terminerinnerungen per E-Mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_lead_days',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Vorlaufzeit für Erinnerungen (Tage)'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=50),
        ),
    ]
