# Generated by Django 5.0.14 on 2026-09-06 16:11

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=255, verbose_name='Tenant-ID')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client-ID')),
                ('client_secret', core.fields.EncryptedTextField(blank=True, default='', verbose_name='Client-Secret')),
                ('sender_address', models.EmailField(blank=True, help_text='Postfach, aus dem gesendet wird. Die App-Registrierung braucht darauf die Application-Permission Mail.Send.', max_length=254, verbose_name='Absenderadresse')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Absendername')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='Antwortadresse')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktiviert den Versand, ohne die Zugangsdaten zu löschen.', verbose_name='Mailversand aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Mail-Konfiguration',
                'verbose_name_plural': 'Mail-Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('recipients', models.TextField(verbose_name='Empfänger')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Betreff')),
                ('template', models.CharField(blank=True, max_length=100, verbose_name='Template')),
                ('status', models.CharField(choices=[('sent', 'versendet'), ('failed', 'fehlgeschlagen'), ('skipped', 'übersprungen')], max_length=10, verbose_name='Status')),
                ('error', models.TextField(blank=True, verbose_name='Fehler')),
            ],
            options={
                'verbose_name': 'Mail-Protokoll',
                'verbose_name_plural': 'Mail-Protokoll',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='services_ma_created_2b2536_idx')],
            },
        ),
    ]
