# Generated by Django 5.0.14 on 2026-09-06 17:16

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('eheim_classicvario', 'Eheim classicVARIO+e'), ('eheim_other', 'Eheim (sonstiges)'), ('shelly_plug', 'Shelly Plug')], max_length=30, verbose_name='Art')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('mac_address', models.CharField(blank=True, help_text='Pflicht bei Eheim-Geräten — jeder Request adressiert das Gerät darüber.', max_length=17, verbose_name='MAC-Adresse')),
                ('host', models.CharField(blank=True, help_text='IP oder Hostname im lokalen Netz.', max_length=200, verbose_name='Adresse')),
                ('credentials', core.fields.EncryptedTextField(blank=True, default='', verbose_name='Zugangsdaten')),
                ('firmware', models.CharField(blank=True, max_length=40, verbose_name='Gerätesoftware')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Geräte werden weder abgefragt noch gesteuert.', verbose_name='aktiv')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='zuletzt erreicht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='angelegt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer')),
            ],
            options={
                'verbose_name': 'Gerät',
                'verbose_name_plural': 'Geräte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('action', models.CharField(max_length=40, verbose_name='Aktion')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('succeeded', models.BooleanField(default=True, verbose_name='erfolgreich')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='services.device', verbose_name='Gerät')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Geräte-Ereignis',
                'verbose_name_plural': 'Geräte-Ereignisse',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('payload', models.JSONField(default=dict, verbose_name='Rohantwort')),
                ('rpm_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Drehzahl (%)')),
                ('pump_mode', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pumpenmodus')),
                ('error_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fehlercode')),
                ('service_due_in', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wartung in (h)')),
                ('is_on', models.BooleanField(blank=True, null=True, verbose_name='eingeschaltet')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='services.device', verbose_name='Gerät')),
            ],
            options={
                'verbose_name': 'Gerätemesswert',
                'verbose_name_plural': 'Gerätemesswerte',
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('mac_address', ''), _negated=True), fields=('owner', 'mac_address'), name='unique_device_mac_per_owner'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', '-occurred_at'], name='services_de_device__5981e0_idx'),
        ),
        migrations.AddIndex(
            model_name='devicereading',
            index=models.Index(fields=['device', '-read_at'], name='services_de_device__7aeeca_idx'),
        ),
    ]
