# Generated by Django 5.0.14 on 2026-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_device_deviceevent_devicereading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='generation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nur bei Shelly: 1 oder 2+. Wird beim ersten Kontakt über /shelly erkannt.', null=True, verbose_name='Generation'),
        ),
        migrations.AddField(
            model_name='device',
            name='tank_label',
            field=models.CharField(blank=True, help_text='Becken, an dem das Gerät hängt — Grundlage der Verbrauchsauswertung.', max_length=120, verbose_name='Becken'),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='energy_total_wh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Zählerstand (Wh)'),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='power_w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Leistung (W)'),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Gerätetemperatur (°C)'),
        ),
    ]
