# Generated by Django 5.0.14 on 2026-09-06 18:14

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_device_generation_device_tank_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', core.fields.EncryptedTextField(blank=True, default='', verbose_name='API-Key')),
                ('model_name', models.CharField(default='claude-opus-5', help_text='Modell-ID von Anthropic, z. B. claude-opus-5, claude-sonnet-5 oder claude-haiku-4-5.', max_length=100, verbose_name='Modell')),
                ('is_enabled', models.BooleanField(default=True, help_text='Schaltet die Assistenz ab, ohne den Key zu löschen.', verbose_name='KI-Funktionen aktiv')),
                ('monthly_token_budget', models.BigIntegerField(default=2000000, help_text='Über alle Benutzer, je Kalendermonat. 0 = ohne Begrenzung.', verbose_name='Token-Budget je Monat')),
                ('per_user_daily_limit', models.IntegerField(default=50000, help_text='0 = ohne Begrenzung.', verbose_name='Token-Limit je Benutzer und Tag')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zuletzt geändert')),
            ],
            options={
                'verbose_name': 'KI-Konfiguration',
                'verbose_name_plural': 'KI-Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('animal', 'Tier'), ('plant', 'Pflanze')], max_length=10, verbose_name='Art')),
                ('scientific_name', models.CharField(blank=True, max_length=160, verbose_name='Wissenschaftlicher Name')),
                ('common_name', models.CharField(blank=True, max_length=160, verbose_name='Deutscher Name')),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Selbsteinschätzung des Modells zwischen 0 und 1 — keine Messgröße.', max_digits=4, null=True, verbose_name='Konfidenz')),
                ('reasoning', models.TextField(blank=True, verbose_name='Begründung')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Entwurf')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('verified', 'bestätigt'), ('rejected', 'verworfen')], default='draft', max_length=10, verbose_name='Status')),
                ('catalog_ref', models.CharField(blank=True, help_text='Gesetzt, sobald der bestätigte Entwurf im Katalog gelandet ist.', max_length=100, verbose_name='Katalogeintrag')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='entschieden am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='erstellt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'KI-Vorschlag',
                'verbose_name_plural': 'KI-Vorschläge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='services_ai_user_id_a79e42_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('identify_animal', 'Tier bestimmen'), ('identify_plant', 'Pflanze bestimmen'), ('profile_animal', 'Steckbrief Tier'), ('profile_plant', 'Steckbrief Pflanze'), ('measurements', 'Messwerte deuten'), ('stocking', 'Besatz prüfen'), ('tank_report', 'Beckenbericht'), ('test', 'Verbindungstest')], max_length=50, verbose_name='Aktion')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modell')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Token Eingabe')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Token Ausgabe')),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Kosten (USD)')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Dauer (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='erfolgreich')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'KI-Verbrauch',
                'verbose_name_plural': 'KI-Verbrauch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='services_ai_created_f6207a_idx'), models.Index(fields=['user', '-created_at'], name='services_ai_user_id_66faa7_idx')],
            },
        ),
    ]
