# Generated by Django 5.0.14 on 2026-09-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_aiconfig_aisuggestion_aiusagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wofür der Token gedacht ist, z. B. „Claude Desktop, Arbeitsrechner“.', max_length=120, verbose_name='Name')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash')),
                ('hint', models.CharField(blank=True, editable=False, help_text='Die ersten Zeichen des Tokens — nur zur Wiedererkennung in der Liste.', max_length=20, verbose_name='Erkennung')),
                ('allow_write', models.BooleanField(default=False, help_text='Ohne Haken kann der Token ausschließlich lesen. Ein Token für reine Auswertungen braucht kein Schreibrecht.', verbose_name='darf schreiben')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='angelegt')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='zuletzt benutzt')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leer = unbegrenzt gültig.', null=True, verbose_name='gültig bis')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='widerrufen am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'MCP-Token',
                'verbose_name_plural': 'MCP-Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(blank=True, max_length=120, verbose_name='Token-Name')),
                ('tool', models.CharField(max_length=60, verbose_name='Werkzeug')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Parameter')),
                ('object_ref', models.CharField(blank=True, help_text='Angelegter Datensatz, z. B. tanks.Measurement:12.', max_length=100, verbose_name='Datensatz')),
                ('succeeded', models.BooleanField(default=True, verbose_name='erfolgreich')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_access_log', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_log', to='services.mcptoken', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'MCP-Protokoll',
                'verbose_name_plural': 'MCP-Protokoll',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mcptoken',
            index=models.Index(fields=['user', '-created_at'], name='services_mc_user_id_09349f_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpaccesslog',
            index=models.Index(fields=['-created_at'], name='services_mc_created_6505e8_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpaccesslog',
            index=models.Index(fields=['user', '-created_at'], name='services_mc_user_id_4a6acd_idx'),
        ),
    ]
