# Generated by Django 5.0.14 on 2026-09-07 13:02

import core.storage
import django.core.validators
import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_device_tank_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="daily_runtime_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Betriebsstunden je Tag für die Verbrauchsschätzung. Leer heißt Dauerbetrieb (24 h) — bei einer Beleuchtung ist das falsch, dort gehört die Brenndauer hinein.",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Laufzeit (h/Tag)",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="flow_rate_lph",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nur bei Filtern und Pumpen.",
                null=True,
                verbose_name="Förderleistung (l/h)",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="power_watts",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Grundlage der Verbrauchsschätzung bei Geräten ohne messende Steckdose.",
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nennleistung (W)",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Kaufpreis (€)",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="purchased_on",
            field=models.DateField(blank=True, null=True, verbose_name="Kaufdatum"),
        ),
        migrations.AddField(
            model_name="device",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Seriennummer"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Lieferant"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="warranty_until",
            field=models.DateField(
                blank=True,
                help_text="Endet die Garantie demnächst, erscheint das als Hinweis auf dem Dashboard.",
                null=True,
                verbose_name="Garantie bis",
            ),
        ),
        migrations.CreateModel(
            name="DeviceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Bedienungsanleitung"),
                            ("invoice", "Rechnung"),
                            ("warranty", "Garantieunterlage"),
                            ("photo", "Foto"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "file",
                    models.FileField(
                        storage=core.storage.PrivateStorage(),
                        upload_to=services.models.device_document_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "heic",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="Datei",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="hochgeladen"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="services.device",
                        verbose_name="Gerät",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerätedokument",
                "verbose_name_plural": "Gerätedokumente",
                "ordering": ["kind", "title"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("url", models.URLField(max_length=500, verbose_name="Adresse")),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Kleinere Zahlen stehen oben.",
                        verbose_name="Reihenfolge",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="services.device",
                        verbose_name="Gerät",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geräte-Link",
                "verbose_name_plural": "Geräte-Links",
                "ordering": ["position", "title"],
            },
        ),
        migrations.CreateModel(
            name="DeviceSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="z. B. „Beckenvolumen“",
                        max_length=80,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="z. B. „60–160“", max_length=160, verbose_name="Wert"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="z. B. „l“ oder „K“",
                        max_length=20,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Kleinere Zahlen stehen oben.",
                        verbose_name="Reihenfolge",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="services.device",
                        verbose_name="Gerät",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technische Angabe",
                "verbose_name_plural": "Technische Angaben",
                "ordering": ["position", "label"],
            },
        ),
    ]
