# Generated by Django 5.0.14 on 2026-09-07 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_device_tank_required'),
        ('tanks', '0004_tank_ai_analysis_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'läuft'), ('ready', 'fertig'), ('failed', 'fehlgeschlagen')], default='running', max_length=10, verbose_name='Status')),
                ('text', models.TextField(blank=True, verbose_name='Auswertung')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modell')),
                ('context_hash', models.CharField(blank=True, help_text='Prüfsumme über alles, was in den Prompt eingeht.', max_length=64, verbose_name='Datenlage')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='erstellt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fertig am')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='tanks.measurement', verbose_name='Messreihe')),
                ('usage_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_analyses', to='services.aiusagelog', verbose_name='Verbrauch')),
            ],
            options={
                'verbose_name': 'KI-Auswertung',
                'verbose_name_plural': 'KI-Auswertungen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['measurement', '-created_at'], name='services_me_measure_33e2af_idx')],
            },
        ),
    ]
