# Generated by Django 5.0.14 on 2026-09-07 15:51

import core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_device_documents_links_specs"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="cover_image",
            field=models.ImageField(
                blank=True, upload_to=core.images.cover_path, verbose_name="Titelbild"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=core.images.cover_thumb_path,
                verbose_name="Titelbild (Kachel)",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="cover_preview",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=core.images.cover_preview_path,
                verbose_name="Titelbild (Vorschau)",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="cover_width",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Titelbildbreite"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="cover_height",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Titelbildhöhe"
            ),
        ),
    ]
