# Generated by Django 5.0.14 on 2026-09-06 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=160)),
                ('variety', models.CharField(blank=True, max_length=80)),
                ('common_name', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('group', models.CharField(choices=[('fisch', 'Fisch'), ('garnele', 'Garnele'), ('krebs', 'Krebs'), ('schnecke', 'Schnecke'), ('muschel', 'Muschel')], max_length=20)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=160)),
                ('size_max_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('min_tank_liters', models.PositiveIntegerField(blank=True, null=True)),
                ('min_tank_length_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_group_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('social_behavior', models.CharField(blank=True, choices=[('einzeln', 'Einzeln'), ('paar', 'Paar'), ('harem', 'Harem'), ('gruppe', 'Gruppe'), ('schwarm', 'Schwarm')], max_length=20)),
                ('zone', models.CharField(blank=True, choices=[('boden', 'Boden'), ('mitte', 'Mitte'), ('oberflaeche', 'Oberfläche')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'einfach'), ('medium', 'mittel'), ('demanding', 'anspruchsvoll')], max_length=20)),
                ('lifespan_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ph_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ph_max', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('kh_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('kh_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gh_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gh_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('diet', models.CharField(blank=True, choices=[('allesfresser', 'Allesfresser'), ('fleisch', 'Fleischfresser'), ('pflanzen', 'Pflanzenfresser'), ('aufwuchs', 'Aufwuchsfresser')], max_length=20)),
                ('breeding_type', models.CharField(blank=True, choices=[('freilaicher', 'Freilaicher'), ('substratlaicher', 'Substratlaicher'), ('hoehlenbrueter', 'Höhlenbrüter'), ('maulbrueter', 'Maulbrüter'), ('lebendgebaerend', 'Lebendgebärend')], max_length=20)),
                ('breeding_notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('care_notes', models.TextField(blank=True)),
                ('compatibility_notes', models.TextField(blank=True)),
                ('warning', models.TextField(blank=True)),
                ('is_line_bred_variant', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scientific_name', 'variety'],
            },
        ),
        migrations.CreateModel(
            name='CatalogAnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/animals/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('maennlich', 'männlich'), ('weiblich', 'weiblich'), ('unbestimmt', 'unbestimmt')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.cataloganimal')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cataloganimal',
            constraint=models.UniqueConstraint(fields=('scientific_name', 'variety'), name='unique_catalog_animal_scientific_name_variety'),
        ),
        migrations.AddConstraint(
            model_name='cataloganimalimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('animal',), name='unique_primary_image_per_animal'),
        ),
    ]
