# Generated by Django 5.0.14 on 2026-09-06 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=160)),
                ('cultivar', models.CharField(blank=True, max_length=80)),
                ('common_name', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=160)),
                ('growth_form', models.CharField(choices=[('stem', 'Stängel'), ('rosette', 'Rosette'), ('epiphyte', 'Aufsitzer'), ('ground_cover', 'Bodendecker'), ('floating', 'Schwimmpflanze'), ('moss', 'Moos')], max_length=20)),
                ('placement', models.CharField(choices=[('foreground', 'Vordergrund'), ('midground', 'Mittelgrund'), ('background', 'Hintergrund')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'einfach'), ('medium', 'mittel'), ('demanding', 'anspruchsvoll')], max_length=20)),
                ('growth_rate', models.CharField(choices=[('slow', 'langsam'), ('medium', 'mittel'), ('fast', 'schnell')], max_length=20)),
                ('light_demand', models.CharField(choices=[('low', 'niedrig'), ('medium', 'mittel'), ('high', 'hoch')], max_length=20)),
                ('co2_demand', models.CharField(choices=[('low', 'niedrig'), ('medium', 'mittel'), ('high', 'hoch')], max_length=20)),
                ('height_min_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_max_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ph_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ph_max', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('kh_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('kh_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('propagation', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('care_notes', models.TextField(blank=True)),
                ('warning', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scientific_name', 'cultivar'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/plants/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.catalogplant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogplant',
            constraint=models.UniqueConstraint(fields=('scientific_name', 'cultivar'), name='unique_catalog_plant_scientific_name_cultivar'),
        ),
        migrations.AddConstraint(
            model_name='catalogplantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('plant',), name='unique_primary_image_per_plant'),
        ),
    ]
