# Generated by Django 5.0.14 on 2026-09-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Katalogberechtigung',
                'verbose_name_plural': 'Katalogberechtigungen',
                'permissions': [('can_edit_catalog', 'Darf den Katalog pflegen')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
