# Generated by Django 5.0.14 on 2026-09-07 11:03

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_catalogpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalimage",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Höhe"
            ),
        ),
        migrations.AddField(
            model_name="animalimage",
            name="preview",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=catalog.models.animal_preview_path,
                verbose_name="Vorschau",
            ),
        ),
        migrations.AddField(
            model_name="animalimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=catalog.models.animal_thumb_path,
                verbose_name="Kachel",
            ),
        ),
        migrations.AddField(
            model_name="animalimage",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Breite"
            ),
        ),
        migrations.AddField(
            model_name="plantimage",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Höhe"
            ),
        ),
        migrations.AddField(
            model_name="plantimage",
            name="preview",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=catalog.models.plant_preview_path,
                verbose_name="Vorschau",
            ),
        ),
        migrations.AddField(
            model_name="plantimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=catalog.models.plant_thumb_path,
                verbose_name="Kachel",
            ),
        ),
        migrations.AddField(
            model_name="plantimage",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Breite"
            ),
        ),
    ]
