# Generated by Django 5.0.14 on 2026-09-07 18:01
#
# Sorte und Zuchtform am Katalog: ``scientific_name`` verliert sein ``unique``
# an eine gemeinsame Bedingung über Name und Sorte. Bestandsdaten brauchen
# dafür keine Umstellung — sie bekommen ``variant=""`` und waren über den
# Namen schon eindeutig, sind es über beide Felder also weiterhin.

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_species_image_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalspecies',
            options={'ordering': [django.db.models.functions.text.Lower('scientific_name'), django.db.models.functions.text.Lower('variant')], 'verbose_name': 'Tierart', 'verbose_name_plural': 'Tierarten'},
        ),
        migrations.AlterModelOptions(
            name='plantspecies',
            options={'ordering': [django.db.models.functions.text.Lower('scientific_name'), django.db.models.functions.text.Lower('variant')], 'verbose_name': 'Pflanzenart', 'verbose_name_plural': 'Pflanzenarten'},
        ),
        migrations.AddField(
            model_name='animalspecies',
            name='is_cultivated_form',
            field=models.BooleanField(default=False, help_text='Durch Selektion entstanden, nicht in der Natur vorkommend.', verbose_name='Zuchtform'),
        ),
        migrations.AddField(
            model_name='animalspecies',
            name='variant',
            field=models.CharField(blank=True, help_text="Sortenbezeichnung wie 'Flamingo', 'Red Ruby', 'Electric Blue'. Leer lassen bei der Stammform.", max_length=80, verbose_name='Sorte / Zuchtform'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='is_cultivated_form',
            field=models.BooleanField(default=False, help_text='Durch Selektion entstanden, nicht in der Natur vorkommend.', verbose_name='Zuchtform'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='variant',
            field=models.CharField(blank=True, help_text="Sortenbezeichnung wie 'Flamingo', 'Red Ruby', 'Electric Blue'. Leer lassen bei der Stammform.", max_length=80, verbose_name='Sorte / Zuchtform'),
        ),
        migrations.AlterField(
            model_name='animalspecies',
            name='scientific_name',
            field=models.CharField(max_length=150, verbose_name='wissenschaftlicher Name'),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='scientific_name',
            field=models.CharField(max_length=150, verbose_name='wissenschaftlicher Name'),
        ),
        migrations.AddConstraint(
            model_name='animalspecies',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('scientific_name'), django.db.models.functions.text.Lower('variant'), name='catalog_animalspecies_unique_variant', violation_error_message='Diese Art gibt es mit dieser Sorte bereits im Katalog.'),
        ),
        migrations.AddConstraint(
            model_name='plantspecies',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('scientific_name'), django.db.models.functions.text.Lower('variant'), name='catalog_plantspecies_unique_variant', violation_error_message='Diese Art gibt es mit dieser Sorte bereits im Katalog.'),
        ),
    ]
