# Generated by Django 5.0.14 on 2026-09-10 10:58
#
# Herkunft an beiden Katalogen, Aufenthaltsbereich, Ernährung und
# Sozialstruktur am Tier, dazu ``SpeciesLink`` für Verweise auf fremde
# Wissensquellen. Alle neuen Felder sind leer zulässig: zu bestehenden
# Steckbriefen ist die Angabe schlicht noch nicht erfasst, und „leer“ ist dabei
# die ehrlichere Auskunft als ein geratener Vorgabewert.
#
# Der ``SpeciesLink`` trägt zwei Fremdschlüssel, von denen die Bedingung
# ``catalog_specieslink_one_species`` genau einen zulässt.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_species_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalspecies',
            name='diet',
            field=models.CharField(blank=True, choices=[('carnivore', 'Fleischlich'), ('herbivore', 'Pflanzlich'), ('omnivore', 'Beides')], max_length=9, verbose_name='Ernährung'),
        ),
        migrations.AddField(
            model_name='animalspecies',
            name='origin_detail',
            field=models.CharField(blank=True, help_text='z. B. „Orinoco-Einzug, Venezuela und Kolumbien“.', max_length=200, verbose_name='Herkunft im Detail'),
        ),
        migrations.AddField(
            model_name='animalspecies',
            name='origin_region',
            field=models.CharField(blank=True, choices=[('south_america', 'Südamerika'), ('central_america', 'Mittelamerika'), ('north_america', 'Nordamerika'), ('africa', 'Afrika'), ('asia', 'Asien'), ('australia', 'Australien / Ozeanien'), ('europe', 'Europa'), ('cultivar', 'Zuchtform ohne Wildvorkommen'), ('unknown', 'Unbekannt')], max_length=15, verbose_name='Verbreitungsgebiet'),
        ),
        migrations.AddField(
            model_name='animalspecies',
            name='social_structure',
            field=models.CharField(blank=True, choices=[('solitary', 'Einzeln'), ('pair', 'Paar (♂ + ♀)'), ('harem', 'Harem (1 ♂ + mehrere ♀)'), ('group', 'Gruppe'), ('shoal', 'Schwarm')], max_length=8, verbose_name='Sozialstruktur'),
        ),
        migrations.AddField(
            model_name='animalspecies',
            name='zone',
            field=models.CharField(blank=True, choices=[('bottom', 'Boden'), ('lower', 'Unterer Bereich'), ('middle', 'Mittlerer Bereich'), ('upper', 'Oberer Bereich'), ('surface', 'Oberfläche'), ('all', 'Alle Bereiche')], max_length=7, verbose_name='Aufenthaltsbereich'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='origin_detail',
            field=models.CharField(blank=True, help_text='z. B. „Orinoco-Einzug, Venezuela und Kolumbien“.', max_length=200, verbose_name='Herkunft im Detail'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='origin_region',
            field=models.CharField(blank=True, choices=[('south_america', 'Südamerika'), ('central_america', 'Mittelamerika'), ('north_america', 'Nordamerika'), ('africa', 'Afrika'), ('asia', 'Asien'), ('australia', 'Australien / Ozeanien'), ('europe', 'Europa'), ('cultivar', 'Zuchtform ohne Wildvorkommen'), ('unknown', 'Unbekannt')], max_length=15, verbose_name='Verbreitungsgebiet'),
        ),
        migrations.CreateModel(
            name='SpeciesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('database', 'Artdatenbank'), ('supplier', 'Hersteller / Händler'), ('article', 'Artikel'), ('forum', 'Forenbeitrag'), ('video', 'Video'), ('other', 'Sonstiges')], default='database', max_length=8, verbose_name='Art der Quelle')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('url', models.URLField(max_length=500, verbose_name='Adresse')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Kleinere Zahlen stehen oben.', verbose_name='Reihenfolge')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.animalspecies', verbose_name='Tierart')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.plantspecies', verbose_name='Pflanzenart')),
            ],
            options={
                'verbose_name': 'Quellenlink',
                'verbose_name_plural': 'Quellenlinks',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='specieslink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('animal__isnull', True), ('plant__isnull', False)), models.Q(('animal__isnull', False), ('plant__isnull', True)), _connector='OR'), name='catalog_specieslink_one_species', violation_error_message='Ein Link gehört zu genau einer Art.'),
        ),
    ]
