# Generated by Django 5.0.14 on 2026-09-10 11:23
#
# Kultivierbarkeit der Pflanzenart — emers, submers oder beides — samt dem
# Freitext, für den die Auswahl zu grob ist. Beide Felder sind leer zulässig:
# zu bestehenden Steckbriefen ist die Angabe schlicht noch nicht erfasst, und
# ein Vorgabewert wäre hier eine Behauptung über die Art.
#
# Das Feld heißt ``growth_form_water`` und nicht ``growth_form``: den Namen
# trägt die Wuchsform (Stängel, Rosette, Aufsitzer) aus #1212 bereits.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_species_links_and_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='emersed_notes',
            field=models.TextField(blank=True, help_text='Blüte, Umgewöhnung, Luftfeuchte — was die Auswahl nicht sagen kann.', verbose_name='Hinweise zur emersen Kultur'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='growth_form_water',
            field=models.CharField(blank=True, choices=[('submersed', 'Nur submers'), ('emersed', 'Nur emers'), ('both', 'Beides')], help_text='Ob die Art über Wasser, unter Wasser oder in beiden Formen dauerhaft wächst. Leer lassen, wenn es nicht erfasst ist.', max_length=9, verbose_name='Kultivierbarkeit'),
        ),
    ]
