# Generated by Django 5.0.14 on 2026-09-06 19:28

import django.db.models.deletion
import tanks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True, verbose_name='Schlüssel')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Einheit')),
                ('decimals', models.PositiveSmallIntegerField(default=1, verbose_name='Nachkommastellen')),
                ('default_min', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Zielbereich min')),
                ('default_max', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Zielbereich max')),
                ('is_key_parameter', models.BooleanField(default=False, help_text='Wird im Verlaufsdiagramm auf dem Dashboard gezeigt.', verbose_name='Leitparameter')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameter',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('water_type', models.CharField(choices=[('fresh', 'Süßwasser'), ('brackish', 'Brackwasser'), ('marine', 'Meerwasser')], default='fresh', max_length=10, verbose_name='Wassertyp')),
                ('volume_liters', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Volumen (l)')),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Länge (cm)')),
                ('width_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Breite (cm)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Höhe (cm)')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Standort')),
                ('setup_date', models.DateField(verbose_name='Einrichtung')),
                ('dissolved_on', models.DateField(blank=True, null=True, verbose_name='Aufgelöst am')),
                ('accent', models.PositiveSmallIntegerField(choices=[(1, 'Farbe 1'), (2, 'Farbe 2'), (3, 'Farbe 3'), (4, 'Farbe 4'), (5, 'Farbe 5'), (6, 'Farbe 6'), (7, 'Farbe 7'), (8, 'Farbe 8')], default=1, help_text='Bestimmt die Farbmarkierung des Beckens in Listen und auf dem Dashboard.', verbose_name='Farbkennung')),
                ('cover_image', models.ImageField(blank=True, upload_to=tanks.models.tank_cover_path, verbose_name='Titelbild')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer')),
            ],
            options={
                'verbose_name': 'Becken',
                'verbose_name_plural': 'Becken',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Anzahl')),
                ('added_on', models.DateField(verbose_name='Eingesetzt am')),
                ('removed_on', models.DateField(blank=True, null=True, verbose_name='Entnommen am')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockings', to='catalog.animalspecies')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockings', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Besatz',
                'verbose_name_plural': 'Besatz',
                'ordering': ['species__scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Anzahl')),
                ('planted_on', models.DateField(verbose_name='Gepflanzt am')),
                ('removed_on', models.DateField(blank=True, null=True, verbose_name='Entfernt am')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='catalog.plantspecies')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Bepflanzung',
                'verbose_name_plural': 'Bepflanzung',
                'ordering': ['species__scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Wert')),
                ('measured_at', models.DateTimeField(verbose_name='Gemessen am')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='tanks.parameter')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Messwert',
                'verbose_name_plural': 'Messwerte',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water_change', 'Wasserwechsel'), ('maintenance', 'Wartung'), ('treatment', 'Behandlung'), ('stocking', 'Besatzänderung'), ('incident', 'Vorfall'), ('other', 'Sonstiges')], default='other', max_length=15, verbose_name='Kategorie')),
                ('title', models.CharField(max_length=160, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('occurred_at', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Ereignis',
                'verbose_name_plural': 'Ereignisse',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('kind', models.CharField(choices=[('filter', 'Filter'), ('heater', 'Heizer'), ('light', 'Beleuchtung'), ('co2', 'CO₂-Anlage'), ('pump', 'Pumpe'), ('doser', 'Dosierpumpe'), ('sensor', 'Sensor'), ('socket', 'Steckdose'), ('other', 'Sonstiges')], default='other', max_length=10, verbose_name='Art')),
                ('manufacturer', models.CharField(blank=True, max_length=80, verbose_name='Hersteller')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='Modell')),
                ('installed_on', models.DateField(blank=True, null=True, verbose_name='In Betrieb seit')),
                ('status', models.CharField(choices=[('ok', 'In Ordnung'), ('warn', 'Abweichung'), ('critical', 'Kritisch'), ('unknown', 'Unbekannt')], default='ok', max_length=10, verbose_name='Status')),
                ('status_message', models.CharField(blank=True, max_length=200, verbose_name='Statusmeldung')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt erreicht')),
                ('maintenance_interval_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wartungsintervall (Tage)')),
                ('last_maintenance_on', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Gerät',
                'verbose_name_plural': 'Geräte',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titel')),
                ('category', models.CharField(choices=[('water_change', 'Wasserwechsel'), ('filter', 'Filterwartung'), ('fertilizer', 'Düngung'), ('test', 'Wassertest'), ('equipment', 'Technik'), ('other', 'Sonstiges')], default='other', max_length=15, verbose_name='Kategorie')),
                ('interval_days', models.PositiveSmallIntegerField(blank=True, help_text='Leer lassen für einmalige Termine.', null=True, verbose_name='Intervall (Tage)')),
                ('due_on', models.DateField(verbose_name='Fällig am')),
                ('last_completed_on', models.DateField(blank=True, null=True, verbose_name='Zuletzt erledigt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['due_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TankParameterTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='min')),
                ('maximum', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='max')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='tanks.parameter')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_targets', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Zielbereich',
                'verbose_name_plural': 'Zielbereiche',
            },
        ),
        migrations.CreateModel(
            name='TankPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tanks.models.tank_photo_path, verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift')),
                ('taken_on', models.DateField(verbose_name='Aufgenommen am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-taken_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(verbose_name='Erledigt am')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tanks.caretask')),
            ],
            options={
                'verbose_name': 'Quittierung',
                'verbose_name_plural': 'Quittierungen',
                'ordering': ['-completed_on', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='tank',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_tank_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['tank', 'parameter', '-measured_at'], name='tanks_measu_tank_id_25050f_idx'),
        ),
        migrations.AddIndex(
            model_name='caretask',
            index=models.Index(fields=['due_on', 'is_active'], name='tanks_caret_due_on_30fb16_idx'),
        ),
        migrations.AddConstraint(
            model_name='tankparametertarget',
            constraint=models.UniqueConstraint(fields=('tank', 'parameter'), name='unique_target_per_tank_parameter'),
        ),
    ]
