# Generated by Django 5.0.14 on 2026-09-06 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('decimals', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=100)),
                ('supports_below_detection', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tanks/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('taken_on', models.DateField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Modellbezeichnung')),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Länge (cm)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Höhe (cm)')),
                ('depth_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tiefe (cm)')),
                ('volume_gross_l', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Bruttovolumen (l)')),
                ('volume_net_l', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Nettovolumen (l)')),
                ('water_type', models.CharField(choices=[('suess', 'Süßwasser'), ('meer', 'Meerwasser'), ('brack', 'Brackwasser')], max_length=10)),
                ('biotope', models.CharField(blank=True, max_length=120)),
                ('started_on', models.DateField(verbose_name='Inbetriebnahme')),
                ('shut_down_on', models.DateField(blank=True, null=True, verbose_name='Auflösung')),
                ('description', models.TextField(blank=True)),
                ('substrate', models.TextField(blank=True, verbose_name='Bodengrund')),
                ('hardscape', models.TextField(blank=True, verbose_name='Hardscape')),
                ('filtration', models.TextField(blank=True, verbose_name='Filterung')),
                ('lighting', models.TextField(blank=True, verbose_name='Beleuchtung')),
                ('co2', models.TextField(blank=True, verbose_name='CO2')),
                ('fertilization', models.TextField(blank=True, verbose_name='Düngung')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tanks.photo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tanks.tank'),
        ),
        migrations.CreateModel(
            name='TankParameterTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tank_targets', to='tanks.parameter')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='tanks.tank')),
            ],
            options={
                'ordering': ['parameter__position', 'parameter__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='tank',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_tank_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='tankparametertarget',
            constraint=models.UniqueConstraint(fields=('tank', 'parameter'), name='unique_tank_parameter_target'),
        ),
    ]
