# Generated by Django 5.0.14 on 2026-09-06 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manuell'), ('device', 'Gerät'), ('import', 'Import')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='tanks.tank')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tanks.measurement'),
        ),
        migrations.CreateModel(
            name='MeasurementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('below_detection', models.BooleanField(default=False, verbose_name='n.n.')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tanks.measurement')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_values', to='tanks.parameter')),
            ],
            options={
                'ordering': ['parameter__position', 'parameter__name'],
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['tank', '-measured_at'], name='tanks_measu_tank_id_f7f451_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementvalue',
            constraint=models.UniqueConstraint(fields=('measurement', 'parameter'), name='unique_measurement_parameter'),
        ),
    ]
