# Generated by Django 5.0.14 on 2026-09-06 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_measurement_photo_measurement_measurementvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('setup', 'Einrichtung'), ('water_change', 'Wasserwechsel'), ('stock', 'Besatz'), ('plants', 'Bepflanzung'), ('tech', 'Technik'), ('fertilizer', 'Düngung'), ('maintenance', 'Pflege'), ('observation', 'Beobachtung'), ('breeding', 'Nachwuchs'), ('disease', 'Krankheit'), ('problem', 'Problem'), ('other', 'Sonstiges')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('water_changed_l', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Wasserwechsel (l)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tanks.tank')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tanks.event'),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('setup', 'Einrichtung'), ('water_change', 'Wasserwechsel'), ('stock', 'Besatz'), ('plants', 'Bepflanzung'), ('tech', 'Technik'), ('fertilizer', 'Düngung'), ('maintenance', 'Pflege'), ('observation', 'Beobachtung'), ('breeding', 'Nachwuchs'), ('disease', 'Krankheit'), ('problem', 'Problem'), ('other', 'Sonstiges')], default='maintenance', max_length=20)),
                ('interval_days', models.PositiveSmallIntegerField(verbose_name='Intervall (Tage)')),
                ('next_due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_done_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='tanks.tank')),
            ],
            options={
                'ordering': ['next_due_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tanks.maintenanceschedule'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tank', '-occurred_at'], name='tanks_event_tank_id_2a40c2_idx'),
        ),
    ]
