# Generated by Django 5.0.14 on 2026-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0003_remove_device_event_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='ai_analysis_mode',
            field=models.CharField(choices=[('auto', 'automatisch nach jeder Messreihe'), ('manual', 'auf Knopfdruck'), ('off', 'aus')], default='manual', help_text='Ohne hinterlegten API-Key hat die Einstellung keine Wirkung.', max_length=10, verbose_name='KI-Auswertung der Messreihen'),
        ),
    ]
