# Generated by Django 5.0.14 on 2026-09-06 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0003_event_photo_event_maintenanceschedule_event_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ['next_due_on']},
        ),
        migrations.RenameField(
            model_name='maintenanceschedule',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='last_done_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='next_due_at',
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='event_category',
            field=models.CharField(choices=[('setup', 'Einrichtung'), ('water_change', 'Wasserwechsel'), ('stock', 'Besatz'), ('plants', 'Bepflanzung'), ('tech', 'Technik'), ('fertilizer', 'Düngung'), ('maintenance', 'Pflege'), ('observation', 'Beobachtung'), ('breeding', 'Nachwuchs'), ('disease', 'Krankheit'), ('problem', 'Problem'), ('other', 'Sonstiges')], default='maintenance', max_length=20, verbose_name='Ereigniskategorie'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='interval',
            field=models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('biweekly', 'Alle 2 Wochen'), ('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('yearly', 'Jährlich'), ('custom', 'Individuell (Tage)')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='last_done_on',
            field=models.DateField(blank=True, null=True, verbose_name='Zuletzt erledigt'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='last_reminded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='lead_days',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Vorlauf (Tage)'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='next_due_on',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Nächster Termin'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Per E-Mail erinnern'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Intervall (Tage)'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tanks.tank'),
        ),
    ]
