# Generated by Django 5.0.14 on 2026-09-06 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_catalog_plant'),
        ('tanks', '0004_reword_maintenance_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('present', 'Vorhanden'), ('temporary', 'Temporär'), ('gone', 'Abgegeben / eingegangen')], default='present', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_male', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity_female', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('added_on', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tank_stock', to='catalog.cataloganimal')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='tanks.tank')),
            ],
            options={
                'ordering': ['animal__scientific_name', 'animal__variety'],
            },
        ),
        migrations.CreateModel(
            name='TankAnimalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Zugang'), ('out', 'Abgang')], max_length=3)),
                ('reason', models.CharField(choices=[('purchase', 'Zukauf'), ('breeding', 'Eigene Nachzucht'), ('transfer_in', 'Umsetzung aus anderem Becken'), ('transfer_out', 'Umsetzung in anderes Becken'), ('sold', 'Verkauft / abgegeben'), ('died', 'Eingegangen'), ('predation', 'Gefressen'), ('jumped', 'Gesprungen'), ('unknown', 'Unbekannt / verschwunden')], max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('occurred_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_movements', to='tanks.event')),
                ('tank_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tanks.tankanimal')),
                ('target_tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tanks.tank')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TankPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('present', 'Vorhanden'), ('temporary', 'Temporär'), ('gone', 'Abgegeben / eingegangen')], default='present', max_length=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('placement', models.CharField(blank=True, max_length=120)),
                ('attached_to', models.CharField(blank=True, max_length=120)),
                ('added_on', models.DateField(blank=True, null=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('identification_certain', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tank_stock', to='catalog.catalogplant')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='tanks.tank')),
            ],
            options={
                'ordering': ['plant__scientific_name', 'plant__cultivar'],
            },
        ),
        migrations.AddConstraint(
            model_name='tankanimal',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='tankanimal_quantity_gte_0'),
        ),
    ]
