# Generated by Django 5.0.14 on 2026-09-07 11:03

import tanks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tanks", "0004_observation_and_event_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tank",
            name="cover_height",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Titelbildhöhe"
            ),
        ),
        migrations.AddField(
            model_name="tank",
            name="cover_preview",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=tanks.models.tank_cover_preview_path,
                verbose_name="Titelbild (Vorschau)",
            ),
        ),
        migrations.AddField(
            model_name="tank",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=tanks.models.tank_cover_thumb_path,
                verbose_name="Titelbild (Kachel)",
            ),
        ),
        migrations.AddField(
            model_name="tank",
            name="cover_width",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Titelbildbreite"
            ),
        ),
        migrations.AddField(
            model_name="tankphoto",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Höhe"
            ),
        ),
        migrations.AddField(
            model_name="tankphoto",
            name="preview",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=tanks.models.tank_preview_path,
                verbose_name="Vorschau",
            ),
        ),
        migrations.AddField(
            model_name="tankphoto",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=tanks.models.tank_thumb_path,
                verbose_name="Kachel",
            ),
        ),
        migrations.AddField(
            model_name="tankphoto",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Breite"
            ),
        ),
    ]
