# Generated by Django 5.0.14 on 2026-09-06 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0005_add_tank_animal_and_plant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-taken_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='taken_on',
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='is_full_tank_shot',
            field=models.BooleanField(default=False, verbose_name='Übersichtsfoto'),
        ),
        migrations.AddField(
            model_name='photo',
            name='taken_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='tanks/%Y/%m/thumbs/'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(check=models.Q(('measurement__isnull', False), ('event__isnull', False), _negated=True), name='photo_not_both_measurement_and_event'),
        ),
    ]
