# Generated by Django 5.0.14 on 2026-09-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0005_image_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardscapeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('wood', 'Wurzel / Holz'), ('stone', 'Stein'), ('botanicals', 'Erlenzapfen, Laub, Seemandelbaumblätter'), ('background', 'Rückwand'), ('cave', 'Höhle / Versteck'), ('other', 'Sonstiges')], default='wood', max_length=12, verbose_name='Art')),
                ('name', models.CharField(help_text='z. B. „Moorkienwurzel“.', max_length=160, verbose_name='Bezeichnung')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Anzahl')),
                ('added_on', models.DateField(blank=True, null=True, verbose_name='Eingebracht am')),
                ('removed_on', models.DateField(blank=True, null=True, verbose_name='Entfernt am')),
                ('affects_water', models.BooleanField(default=False, verbose_name='Wirkt auf die Wasserwerte')),
                ('water_effect', models.CharField(blank=True, help_text='z. B. „Huminstoffe, senkt pH“.', max_length=200, verbose_name='Wirkung')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardscape', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Hardscape',
                'verbose_name_plural': 'Hardscape',
                'ordering': [models.OrderBy(models.F('removed_on'), nulls_first=True), 'kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubstrateLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='0 ist die unterste Schicht.', verbose_name='Position')),
                ('kind', models.CharField(choices=[('nutrient', 'Nährstoffdepot'), ('soil', 'Aquasoil'), ('gravel', 'Kies'), ('sand', 'Sand'), ('lava', 'Lavagranulat'), ('filter_mat', 'Filtermatte / Trennschicht'), ('other', 'Sonstiges')], default='gravel', max_length=12, verbose_name='Art')),
                ('product', models.CharField(blank=True, help_text='z. B. „Dennerle Sansibar“.', max_length=160, verbose_name='Produkt')),
                ('grain_size', models.CharField(blank=True, help_text='z. B. „0,5–1 mm“.', max_length=60, verbose_name='Körnung')),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Mächtigkeit (cm)')),
                ('added_on', models.DateField(blank=True, null=True, verbose_name='Eingebracht am')),
                ('depleted_on', models.DateField(blank=True, help_text='Bei Depots das rechnerische Ende der Standzeit.', null=True, verbose_name='Erschöpft am')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substrate_layers', to='tanks.tank')),
            ],
            options={
                'verbose_name': 'Bodengrundschicht',
                'verbose_name_plural': 'Bodengrund',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
