# Generated by Django 5.0.14 on 2026-09-07 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0007_derived_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='below_detection',
            field=models.BooleanField(default=False, help_text='Der Test hat unterhalb seiner Nachweisgrenze nichts angezeigt.', verbose_name='nicht nachweisbar'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='detection_limit',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Leer lassen, wenn der Parameter keine hat (pH, Temperatur, KH).', max_digits=8, null=True, verbose_name='Nachweisgrenze'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Wert'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('below_detection', False), ('value__isnull', False)), models.Q(('below_detection', True), ('value__isnull', True)), _connector='OR'), name='measurement_value_xor_below_detection'),
        ),
    ]
