# Generated by Django 5.0.14 on 2026-09-08 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_species_variant'),
        ('tanks', '0009_detection_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('animal', 'Tiere'), ('plant', 'Pflanzen')], max_length=6, verbose_name='Art')),
                ('quantity', models.PositiveIntegerField(verbose_name='Anzahl')),
                ('moved_on', models.DateField(verbose_name='Umgesetzt am')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='catalog.animalspecies', verbose_name='Tierart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='catalog.plantspecies', verbose_name='Pflanzenart')),
                ('source_tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='tanks.tank', verbose_name='Quellbecken')),
                ('target_tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='tanks.tank', verbose_name='Zielbecken')),
            ],
            options={
                'verbose_name': 'Umzug',
                'verbose_name_plural': 'Umzüge',
                'ordering': ['-moved_on', '-pk'],
                'indexes': [models.Index(fields=['target_tank', 'kind', 'moved_on'], name='tanks_trans_target__372c78_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('source_tank', models.F('target_tank')), _negated=True), name='transfer_between_two_tanks', violation_error_message='Quell- und Zielbecken sind dasselbe Becken.'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('animal__isnull', False), ('kind', 'animal'), ('plant__isnull', True)), models.Q(('animal__isnull', True), ('kind', 'plant'), ('plant__isnull', False)), _connector='OR'), name='transfer_species_matches_kind'),
        ),
    ]
