# Generated by Django 5.0.14 on 2026-09-10 11:05

#
# Bezugsquelle am Besatz- und Pflanzeneintrag, dazu die Geschlechterverteilung
# am Besatz. Beides gehört an den Eintrag und nicht in den Katalog: dieselbe Art
# kann aus ganz verschiedenen Quellen stammen. Die Auswahllisten sind je Modell
# eigene — Wildfang und Nachzucht beim Tier, InVitro und Vorkultur bei der
# Pflanze.
#
# Alles leer bzw. ``null`` zulässig: zu Bestandsdaten ist die Angabe nicht
# nachträglich zu erfinden, und bei einem Schwarm zählt die Geschlechter
# niemand.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0010_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='provenance',
            field=models.CharField(blank=True, choices=[('in_vitro', 'InVitro'), ('submersed', 'Submers vorgezogen'), ('emersed', 'Emers vorgezogen'), ('own_cutting', 'Eigener Ableger'), ('retail', 'Handel, Herkunft unbekannt'), ('unknown', 'Unbekannt')], max_length=11, verbose_name='Bezugsquelle'),
        ),
        migrations.AddField(
            model_name='planting',
            name='provenance_detail',
            field=models.CharField(blank=True, help_text='Woher die Pflanzen kamen.', max_length=200, verbose_name='Gärtnerei / Händler'),
        ),
        migrations.AddField(
            model_name='stocking',
            name='provenance',
            field=models.CharField(blank=True, choices=[('wild', 'Wildfang'), ('bred_local', 'Eigene Nachzucht'), ('bred_de', 'Deutsche / europäische Nachzucht'), ('bred_asia', 'Asiatische Nachzucht'), ('retail', 'Handel, Herkunft unbekannt'), ('unknown', 'Unbekannt')], max_length=10, verbose_name='Bezugsquelle'),
        ),
        migrations.AddField(
            model_name='stocking',
            name='provenance_detail',
            field=models.CharField(blank=True, help_text='Wer die Tiere abgegeben hat.', max_length=200, verbose_name='Züchter / Händler'),
        ),
        migrations.AddField(
            model_name='stocking',
            name='quantity_female',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='davon Weibchen'),
        ),
        migrations.AddField(
            model_name='stocking',
            name='quantity_male',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='davon Männchen'),
        ),
    ]
